version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=camdev
      - MYSQL_USER=mariachi
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=mariachi
      - PMA_PASSWORD=admin123
    ports:
      - 8080:80
